name: "diff"
version: "0.1"
usage: "Preview helm upgrade changes as three way merge patch"
description: "Preview helm upgrade changes as a three way merge patch"
useTunnel: true
command: "$HELM_PLUGIN_DIR/bin/helmdiff"
hooks:
  install: "$HELM_PLUGIN_DIR/install-binary.sh"
  update: "$HELM_PLUGIN_DIR/install-binary.sh"